services:
  pg-app:
    image: postgres
    container_name: pg-app
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pg-app-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pg-auth:
    image: postgres
    container_name: pg-auth
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pg-auth-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  pg-app-data:
  pg-auth-data:
